version: "3.8"

services:
  cs-subscribe-authorization-api:
    build:
      context: .
      dockerfile: Dockerfile
    networks:
      - cs-subscribe
    ports:
      - "8080:8080"
    tty: true

  cs-subscribe-redis: 
    image: redis
    ports:
      - 6379:6379
    networks:
      - cs-subscribe

networks:
  cs-subscribe:
    external: true