services:
  cs-subscribe-authorization-api-dev:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ../:/app/authorization
    tty: true
    working_dir: /app/authorization
  
  cs-subscribe-redis: 
    image: redis
    ports:
      - 6379:6379
  
